/*
 * File: LQR_K_WBR.c
 *
 * MATLAB Coder version            : 24.1
 * C/C++ source code generated on  : 2026-07-27 15:02:48
 */

/* Include Files */
#include "lqr_gain_table.h"

/* Function Definitions */
/*
 * LQR_K_WBR
 *     K_sym = LQR_K_WBR(lL,lR)
 *
 * Arguments    : float lL
 *                float lR
 *                float K_sym[40]
 * Return Type  : void
 */
void LQR_K_WBR(float lL, float lR, float K_sym[40])
{
  float K_sym_tmp;
  float K_sym_tmp_tmp;
  float b_K_sym_tmp;
  float c_K_sym_tmp;
  float d_K_sym_tmp;
  float e_K_sym_tmp;
  float f_K_sym_tmp;
  float g_K_sym_tmp;
  float h_K_sym_tmp;
  float t2;
  float t3;
  /*     This function was generated by the Symbolic Math Toolbox version 24.1.
   */
  /*     2026-07-27 15:02:39 */
  t2 = lL * lL;
  t3 = lR * lR;
  K_sym_tmp_tmp = lL * lR;
  K_sym_tmp = K_sym_tmp_tmp * 0.394434452F;
  K_sym[0] = ((((lL * 1.35945499F - lR * 3.81089163F) - t2 * 2.06506157F) +
               t3 * 7.03364897F) +
              K_sym_tmp) -
             0.895083785F;
  K_sym[1] = ((((lL * -3.81089163F + lR * 1.35945499F) + t2 * 7.03364897F) -
               t3 * 2.06506157F) +
              K_sym_tmp) -
             0.895083785F;
  K_sym_tmp = K_sym_tmp_tmp * 7.01777363F;
  K_sym[2] = ((((lL * -5.41786146F - lR * 13.0414286F) + t2 * 10.4970341F) +
               t3 * 16.2367897F) +
              K_sym_tmp) +
             2.64064217F;
  K_sym[3] = ((((lL * -13.0414286F - lR * 5.41786146F) + t2 * 16.2367897F) +
               t3 * 10.4970341F) +
              K_sym_tmp) +
             2.64064217F;
  K_sym_tmp = K_sym_tmp_tmp * 0.717671F;
  K_sym[4] = ((((lL * 0.842964113F - lR * 3.05331731F) - t2 * 1.74410832F) +
               t3 * 4.94098091F) +
              K_sym_tmp) -
             0.723174036F;
  K_sym[5] = ((((lL * -3.05331731F + lR * 0.842964113F) + t2 * 4.94098091F) -
               t3 * 1.74410832F) +
              K_sym_tmp) -
             0.723174036F;
  K_sym_tmp = K_sym_tmp_tmp * 4.64158583F;
  K_sym[6] = ((((lL * -4.00818682F - lR * 10.5251932F) + t2 * 9.5995245F) +
               t3 * 12.2143869F) +
              K_sym_tmp) +
             2.12511516F;
  K_sym[7] = ((((lL * -10.5251932F - lR * 4.00818682F) + t2 * 12.2143869F) +
               t3 * 9.5995245F) +
              K_sym_tmp) +
             2.12511516F;
  K_sym_tmp = K_sym_tmp_tmp * 0.259471297F;
  K_sym[8] = ((((lL * -0.332809418F + lR * 0.645037532F) + t2 * 0.681174576F) -
               t3 * 1.44569016F) +
              K_sym_tmp) -
             0.299875379F;
  K_sym[9] = ((((lL * -0.645037532F + lR * 0.332809418F) + t2 * 1.44569016F) -
               t3 * 0.681174576F) -
              K_sym_tmp) +
             0.299875379F;
  K_sym_tmp = K_sym_tmp_tmp * 1.31968427F;
  K_sym[10] = ((((lL * 1.30668068F + lR * 0.778691292F) - t2 * 3.02029181F) -
                t3 * 1.98750675F) +
               K_sym_tmp) +
              0.151237309F;
  K_sym[11] = ((((lL * -0.778691292F - lR * 1.30668068F) + t2 * 1.98750675F) +
                t3 * 3.02029181F) -
               K_sym_tmp) -
              0.151237309F;
  K_sym_tmp = K_sym_tmp_tmp * 0.273180366F;
  K_sym[12] = ((((lL * -0.358958215F + lR * 0.673733234F) + t2 * 0.708456874F) -
                t3 * 1.46264267F) +
               K_sym_tmp) -
              0.28708753F;
  K_sym[13] = ((((lL * -0.673733234F + lR * 0.358958215F) + t2 * 1.46264267F) -
                t3 * 0.708456874F) -
               K_sym_tmp) +
              0.28708753F;
  K_sym_tmp = K_sym_tmp_tmp * 1.43513262F;
  K_sym[14] = ((((lL * 1.37621891F + lR * 0.833023369F) - t2 * 3.09568286F) -
                t3 * 2.01281428F) +
               K_sym_tmp) +
              0.131683916F;
  K_sym[15] = ((((lL * -0.833023369F - lR * 1.37621891F) + t2 * 2.01281428F) +
                t3 * 3.09568286F) -
               K_sym_tmp) -
              0.131683916F;
  K_sym_tmp = K_sym_tmp_tmp * 8.75657F;
  K_sym[16] = ((((lL * -6.3278079F + lR * 2.45899F) + t2 * 5.64134264F) -
                t3 * 4.95185757F) +
               K_sym_tmp) -
              1.03456187F;
  b_K_sym_tmp = K_sym_tmp_tmp * 1.22541106F;
  K_sym[17] = ((((lL * -14.0321484F + lR * 3.855551F) + t2 * 18.427084F) -
                t3 * 6.14085388F) -
               b_K_sym_tmp) -
              0.906187F;
  c_K_sym_tmp = K_sym_tmp_tmp * 28.8380947F;
  K_sym[18] = ((((lL * 8.58962536F - lR * 0.375050277F) - t2 * 0.314860582F) -
                t3 * 3.44268799F) +
               c_K_sym_tmp) +
              4.58211279F;
  d_K_sym_tmp = K_sym_tmp_tmp * 27.9665203F;
  K_sym[19] = ((((lL * -27.4483929F - lR * 11.4013557F) + t2 * 30.677206F) +
                t3 * 23.9885178F) -
               d_K_sym_tmp) +
              1.72061443F;
  e_K_sym_tmp = K_sym_tmp_tmp * 1.14885652F;
  K_sym[20] = ((((lL * -0.982444942F - lR * 0.188739508F) + t2 * 0.111875504F) +
                t3 * 0.00490192417F) +
               e_K_sym_tmp) -
              0.0250415057F;
  f_K_sym_tmp = K_sym_tmp_tmp * 0.528032899F;
  K_sym[21] = ((((lL * -1.64411449F + lR * 0.159557268F) + t2 * 0.828932822F) -
                t3 * 0.471545964F) +
               f_K_sym_tmp) -
              0.0728734136F;
  g_K_sym_tmp = K_sym_tmp_tmp * 1.69837093F;
  K_sym[22] = ((((lL * -1.75235593F - lR * 0.700999677F) + t2 * 7.53530693F) +
                t3 * 0.489725858F) +
               g_K_sym_tmp) +
              0.784009337F;
  h_K_sym_tmp = K_sym_tmp_tmp * 4.20835876F;
  K_sym[23] = ((((lL * -2.22950149F - lR * 0.169597372F) + t2 * 0.274743557F) +
                t3 * 1.63666975F) -
               h_K_sym_tmp) +
              0.159376934F;
  K_sym[24] = ((((lL * 3.855551F - lR * 14.0321484F) - t2 * 6.14085388F) +
                t3 * 18.427084F) -
               b_K_sym_tmp) -
              0.906187F;
  K_sym[25] = ((((lL * 2.45899F - lR * 6.3278079F) - t2 * 4.95185757F) +
                t3 * 5.64134264F) +
               K_sym_tmp) -
              1.03456187F;
  K_sym[26] = ((((lL * -11.4013557F - lR * 27.4483929F) + t2 * 23.9885178F) +
                t3 * 30.677206F) -
               d_K_sym_tmp) +
              1.72061443F;
  K_sym[27] = ((((lL * -0.375050277F + lR * 8.58962536F) - t2 * 3.44268799F) -
                t3 * 0.314860582F) +
               c_K_sym_tmp) +
              4.58211279F;
  K_sym[28] = ((((lL * 0.159557268F - lR * 1.64411449F) - t2 * 0.471545964F) +
                t3 * 0.828932822F) +
               f_K_sym_tmp) -
              0.0728734136F;
  K_sym[29] =
      ((((lL * -0.188739508F - lR * 0.982444942F) + t2 * 0.00490192417F) +
        t3 * 0.111875504F) +
       e_K_sym_tmp) -
      0.0250415057F;
  K_sym[30] = ((((lL * -0.169597372F - lR * 2.22950149F) + t2 * 1.63666975F) +
                t3 * 0.274743557F) -
               h_K_sym_tmp) +
              0.159376934F;
  K_sym[31] = ((((lL * -0.700999677F - lR * 1.75235593F) + t2 * 0.489725858F) +
                t3 * 7.53530693F) +
               g_K_sym_tmp) +
              0.784009337F;
  K_sym_tmp = K_sym_tmp_tmp * 2.27941346F;
  K_sym[32] = ((((lL * 4.6869154F + lR * 6.0995059F) - t2 * 7.20223522F) -
                t3 * 8.23047352F) -
               K_sym_tmp) -
              2.33239555F;
  K_sym[33] = ((((lL * 6.0995059F + lR * 4.6869154F) - t2 * 8.23047352F) -
                t3 * 7.20223522F) -
               K_sym_tmp) -
              2.33239555F;
  K_sym_tmp = K_sym_tmp_tmp * 4.5144186F;
  K_sym[34] = ((((lL * -26.1989861F + lR * 3.96474934F) + t2 * 46.2428703F) -
                t3 * 5.54937029F) +
               K_sym_tmp) -
              1.18351626F;
  K_sym[35] = ((((lL * 3.96474934F - lR * 26.1989861F) - t2 * 5.54937029F) +
                t3 * 46.2428703F) +
               K_sym_tmp) -
              1.18351626F;
  K_sym_tmp = K_sym_tmp_tmp * 0.0365565829F;
  K_sym[36] = ((((lL * 0.902937114F + lR * 1.9298104F) - t2 * 1.68466985F) -
                t3 * 3.34927034F) +
               K_sym_tmp) -
              0.509012759F;
  K_sym[37] = ((((lL * 1.9298104F + lR * 0.902937114F) - t2 * 3.34927034F) -
                t3 * 1.68466985F) +
               K_sym_tmp) -
              0.509012759F;
  K_sym_tmp = K_sym_tmp_tmp * 0.108686268F;
  K_sym[38] = ((((lL * -6.85567617F + lR * 2.26465392F) + t2 * 13.6470795F) -
                t3 * 4.1150918F) +
               K_sym_tmp) -
              0.642435491F;
  K_sym[39] = ((((lL * 2.26465392F - lR * 6.85567617F) - t2 * 4.1150918F) +
                t3 * 13.6470795F) +
               K_sym_tmp) -
              0.642435491F;
}

/*
 * File trailer for LQR_K_WBR.c
 *
 * [EOF]
 */
