<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>template_middleware</name>
  <version>0.1.0</version>
  <description>WheelBipe unified MuJoCo and real-hardware bringup.</description>
  <maintainer email="2231625449@qq.com">SCUTRobotLab</maintainer>
  <license>MIT</license>
  <url type="website">https://www.scutbot.cn/</url>
  <author>SCUTRobotLab</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>keyboard_teleop</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>mujoco_ros2_control</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>real_bridge</exec_depend>
  <exec_depend>robot_descriptions</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>template_ros2_controller</exec_depend>
  <exec_depend>xbox_teleop</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
