/* Generated by tools/s2r_build_info.py. */
#ifndef S2R_BUILD_INFO_H
#define S2R_BUILD_INFO_H
#define S2R_SOURCE_SHA256 "74cb2b909db0fc73dab7daff28d154ad0a7046ff0606b09bc292e4209dfbe325"
#define S2R_CONFIG_SHA256 "480118b76bd7de9cf3146719828b8d954d3b3617f4c2277fdb5903d2d6c5ed48"
#define S2R_BUILD_JSON "{\"base_commit\":\"282aed4b6683e497b1795bba45bdab9975e2a201\",\"dirty_at_generation\":true,\"source_sha256\":\"74cb2b909db0fc73dab7daff28d154ad0a7046ff0606b09bc292e4209dfbe325\",\"identity_rule\":\"source digest identifies the source set; regenerate before every build\"}"
#define S2R_MODEL_JSON "{\"name\":\"model_6000_h723.onnx\",\"hash_algorithm\":\"MD5\",\"hash\":\"4899195601babb22a7c0b46cc151ad84\",\"backend\":\"STM32Cube.AI\",\"input_shapes\":[[1,25],[1,125]],\"output_shapes\":[[1,6],[1,3]],\"numeric_type\":\"float32\"}"
#endif
